### ISSUE TITLE
PhpMyAdmin : Remise à zéro d'une colonne AUTO_INCREMENT

### ISSUE THREAD

**Issue by vykio** [vykio/Projet-ING1-Offre-de-Stage#11]
Remise à zéro de la colonne "id" ne fonctionne pas sur PHPMyAdmin.
Expérimenté par gogo

Mettre la solution du problème dans ce thread

**Comment by gauthierleurette** [comment]
J'ai trouvé sur de la documentation mySQL :

> Note that you cannot reset the counter to a value less than or equal to any that have already been 
 used.

Donc si on veut remettre à zéro l'id, il faut : 

1. Supprimer toutes les données et remettre manuellement le compteur à zéro (Pas une solution durable).

**=>Ne fonctionne pas, on retourne quand même à la dernière valeur qu'à eu l'ID !**


2. Utiliser cette solution :

> Truncate table automatically reset the Autoincrement values to 0.

`TRUNCATE` TABLE `table_name;`

> Use this with caution. When Truncation is used, it resets any AUTO_INCREMENT counter to zero. From MySQL 5.0.13 on, the AUTO_INCREMENT counter is reset to zero by TRUNCATE TABLE, regardless of whether there is a foreign key constraint. Once TRUNCATE is fired, the table handler does not remember the last used AUTO_INCREMENT value, but starts counting from the beginning. This is true even for MyISAM and InnoDB, which normally do not reuse sequence values."

Ici il faut tester pour voir ce que ça fait concrètement, pour s'assurer que ça n'utilise pas les IDs déjà affectés et si on repart bien à partir de la plus grande valeur de l'ID.

**=>Cette solution fonctionne mais supprime tout ce que contient la table donc c'est pas viable**

SOURCE : https://www.viralpatel.net/reseting-mysql-autoincrement-column/

**Comment by vykio** [comment]
C'est vrai qu'il fallait vider la table avant de remettre le AUTO_INCREMENT à zéro.
T'as essayé une solution ?

**Comment by gauthierleurette** [comment]
Oui j'ai essayé mais ça ne fonctionne pas, on reprends l'incrémentation à la dernière valeur d'id enregistrée :/ 
La deuxième solution est pas convaincante parce qu'elle supprime toute les données.

**Comment by vykio** [comment]
c'est bizarre car moi ça avait fonctionné

**Comment by vykio** [comment]
Sur mon PhpMA:
- Je sélectionne toute la table, je supprimer mes éléments.
- Je vais dans Opérations -> et je reset le AUTO_INCREMENT à 1 (prochain ID utilisable)
- Je fais éxecuter juste en dessous

et lors de ma prochaine connexion - ou inscription pour toi -  l'id devrait être 1

Je comprends pas pourquoi ça marche pas, je viens d'essayer sur ma BDD

**Comment by vykio** [comment]
Mon moteur de stockage sur cette table c'est du MyISAM

**Comment by gauthierleurette** [comment]
Alors là je comprends pas je viens de refaire la manip et ça a fonctionné :')
J'ai le même moteur de stockage
